### ISSUE TITLE
Have an option to NOT change the background colour for NPCs/creatures

### ISSUE THREAD

**Issue by farling42** [gonzaPaEst/cyphercombat#8]
In the default FVTT tracker, the background colours are the same for all entries other than the current combatant.

It would be nice to have an option in your module to disable the different background colours for the different actor types - keeping only a different background for the current turn's Actor and the hover-highlight background colour.

The reason is that I am one of the 5% of men with red-green colour-blindness, and having multiple background colours makes the combat tracker less usable when trying to see which entry has changed when hovering the mouse over the token.

**Comment by gonzaPaEst** [comment]
Very important request for accessibility purposes.

I am pushing those changes today. The option to remove the background colors will be placed in the Module Settings.

**Comment by farling42** [comment]
Many thanks for the rapid response :)
